-- Zajel phase 6 and 7 schema. No secrets and no web redirects.
create table if not exists channels(id uuid primary key default uuid_generate_v4(),title text not null,description text,owner_id uuid references auth.users(id) on delete cascade,is_private boolean default false,created_at timestamptz default now());
create table if not exists channel_members(id uuid primary key default uuid_generate_v4(),channel_id uuid references channels(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text default 'member',created_at timestamptz default now(),unique(channel_id,user_id));
create table if not exists channel_posts(id uuid primary key default uuid_generate_v4(),channel_id uuid references channels(id) on delete cascade,author_id uuid references auth.users(id) on delete cascade,body text not null,created_at timestamptz default now());
create table if not exists channel_invites(id uuid primary key default uuid_generate_v4(),channel_id uuid references channels(id) on delete cascade,token text unique not null default encode(gen_random_bytes(18),'hex'),created_by uuid references auth.users(id),created_at timestamptz default now(),expires_at timestamptz,used_at timestamptz);
create table if not exists communities(id uuid primary key default uuid_generate_v4(),title text not null,description text,owner_id uuid references auth.users(id) on delete cascade,created_at timestamptz default now());
create table if not exists community_members(id uuid primary key default uuid_generate_v4(),community_id uuid references communities(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text default 'member',unique(community_id,user_id));
create table if not exists community_groups(community_id uuid references communities(id) on delete cascade,group_id uuid references groups(id) on delete cascade,primary key(community_id,group_id));
create table if not exists community_channels(community_id uuid references communities(id) on delete cascade,channel_id uuid references channels(id) on delete cascade,primary key(community_id,channel_id));
alter table channels enable row level security;alter table channel_members enable row level security;alter table channel_posts enable row level security;alter table channel_invites enable row level security;alter table communities enable row level security;alter table community_members enable row level security;alter table community_groups enable row level security;alter table community_channels enable row level security;
drop policy if exists "channels_public_or_member" on channels;
create policy "channels_public_or_member" on channels for select using(not is_private or owner_id=auth.uid() or exists(select 1 from channel_members m where m.channel_id=id and m.user_id=auth.uid()));
drop policy if exists "channels_owner_insert" on channels;
create policy "channels_owner_insert" on channels for insert with check(owner_id=auth.uid());
drop policy if exists "channel_members_self_or_owner" on channel_members;
create policy "channel_members_self_or_owner" on channel_members for insert with check(user_id=auth.uid() or exists(select 1 from channels c where c.id=channel_id and c.owner_id=auth.uid()));
drop policy if exists "channel_posts_visible" on channel_posts;
create policy "channel_posts_visible" on channel_posts for select using(exists(select 1 from channels c where c.id=channel_id and(not c.is_private or c.owner_id=auth.uid() or exists(select 1 from channel_members m where m.channel_id=c.id and m.user_id=auth.uid()))));
drop policy if exists "channel_posts_owner" on channel_posts;
create policy "channel_posts_owner" on channel_posts for insert with check(author_id=auth.uid() and exists(select 1 from channels c where c.id=channel_id and(c.owner_id=auth.uid() or exists(select 1 from channel_members m where m.channel_id=c.id and m.user_id=auth.uid() and m.role in('owner','admin')))));
drop policy if exists "communities_member_select" on communities;
create policy "communities_member_select" on communities for select using(owner_id=auth.uid() or exists(select 1 from community_members m where m.community_id=id and m.user_id=auth.uid()));
drop policy if exists "communities_owner_insert" on communities;
create policy "communities_owner_insert" on communities for insert with check(owner_id=auth.uid());
drop policy if exists "community_members_self" on community_members;
create policy "community_members_self" on community_members for insert with check(user_id=auth.uid() or exists(select 1 from communities c where c.id=community_id and c.owner_id=auth.uid()));
