package com.zajel.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import com.zajel.app.core.*;import com.zajel.app.data.*;import com.zajel.app.domain.*;import java.util.*;
public final class MainActivity extends Activity { LinearLayout root; EditText email,password; AppContainer c; TextView status;
 public void onCreate(Bundle b){super.onCreate(b);c=((ZajelApplication)getApplication()).container();if(c.auth.current()!=null)showHome();else showAuth();}
 TextView title(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(26);v.setTextColor(Color.rgb(24,45,61));v.setPadding(0,0,0,28);return v;}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(40,70,40,30);root.setBackgroundColor(Color.WHITE);setContentView(root);}
 void showAuth(){base();root.addView(title("Zajel"));TextView intro=new TextView(this);intro.setText("Sign in to your account");intro.setTextSize(18);root.addView(intro);email=new EditText(this);email.setHint("Email");password=new EditText(this);password.setHint("Password");password.setInputType(129);root.addView(email);root.addView(password);Button in=new Button(this);in.setText("Sign in");Button up=new Button(this);up.setText("Create account");root.addView(in);root.addView(up);status=new TextView(this);root.addView(status);in.setOnClickListener(v->auth(false));up.setOnClickListener(v->auth(true));}
 void auth(boolean signup){status.setText("Connecting…");AuthRepository.Callback<UserSession> cb=new AuthRepository.Callback<UserSession>(){public void success(UserSession s){runOnUiThread(()->showHome());}public void error(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}};if(signup)c.auth.signUp(email.getText().toString().trim(),password.getText().toString(),cb);else c.auth.signIn(email.getText().toString().trim(),password.getText().toString(),cb);}
 void showHome(){base();root.addView(title("Home"));TextView hint=new TextView(this);hint.setText("Your conversations");hint.setTextSize(18);root.addView(hint);ListView list=new ListView(this);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));status=new TextView(this);root.addView(status);Button profile=new Button(this);profile.setText("Profile and settings");root.addView(profile);profile.setOnClickListener(v->showProfile());loadConversations(list);}
 void loadConversations(ListView list){status.setText("Loading…");c.chats.conversations(new ChatRepository.Callback<List<Conversation>>(){public void success(List<Conversation> value){runOnUiThread(()->{status.setText(value.isEmpty()?"No conversations yet":"");String[] labels=new String[value.size()];for(int i=0;i<value.size();i++)labels[i]=value.get(i).title;list.setAdapter(new ArrayAdapter<String>(MainActivity.this,android.R.layout.simple_list_item_1,labels));list.setOnItemClickListener((p,v,pos,id)->showChat(value.get(pos)));});}public void error(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}});}
 void showChat(Conversation conversation){base();root.addView(title(conversation.title));ListView list=new ListView(this);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));LinearLayout composer=new LinearLayout(this);EditText input=new EditText(this);input.setHint("Message");Button send=new Button(this);send.setText("Send");composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));composer.addView(send);root.addView(composer);status=new TextView(this);root.addView(status);Button back=new Button(this);back.setText("Back to Home");root.addView(back);back.setOnClickListener(v->showHome());loadMessages(conversation.id,list);send.setOnClickListener(v->{String text=input.getText().toString().trim();if(text.isEmpty())return;send.setEnabled(false);c.chats.sendText(conversation.id,text,new ChatRepository.Callback<Message>(){public void success(Message m){runOnUiThread(()->{input.setText("");send.setEnabled(true);loadMessages(conversation.id,list);});}public void error(Exception e){runOnUiThread(()->{send.setEnabled(true);status.setText(e.getMessage());});}});});}
 void loadMessages(String id,ListView list){status.setText("Loading messages…");c.chats.messages(id,new ChatRepository.Callback<List<Message>>(){public void success(List<Message> value){runOnUiThread(()->{status.setText(value.isEmpty()?"No messages yet":"");String[] labels=new String[value.size()];for(int i=0;i<value.size();i++)labels[i]=value.get(i).body;list.setAdapter(new ArrayAdapter<String>(MainActivity.this,android.R.layout.simple_list_item_1,labels));});}public void error(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}});}
 void showProfile(){base();root.addView(title("Your profile"));EditText user=new EditText(this);user.setHint("Username");EditText name=new EditText(this);name.setHint("Display name");EditText avatar=new EditText(this);avatar.setHint("Avatar URL (optional)");root.addView(user);root.addView(name);root.addView(avatar);Button save=new Button(this);save.setText("Save profile");Button settings=new Button(this);settings.setText("Basic settings");Button out=new Button(this);out.setText("Sign out");root.addView(save);root.addView(settings);root.addView(out);status=new TextView(this);root.addView(status);c.profiles.get(new ProfileRepository.Callback<Profile>(){public void success(Profile p){runOnUiThread(()->{user.setText(p.username);name.setText(p.displayName);avatar.setText(p.avatarUrl);});}public void error(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}});save.setOnClickListener(v->c.profiles.update(user.getText().toString(),name.getText().toString(),avatar.getText().toString(),new ProfileRepository.Callback<Profile>(){public void success(Profile p){runOnUiThread(()->status.setText("Profile saved"));}public void error(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}}));settings.setOnClickListener(v->showSettings());out.setOnClickListener(v->{c.auth.signOut();showAuth();});}
 void showSettings(){base();root.addView(title("Settings"));Switch n=new Switch(this);n.setText("Notifications");Switch p=new Switch(this);p.setText("Show online presence");root.addView(n);root.addView(p);Button back=new Button(this);back.setText("Back to profile");root.addView(back);back.setOnClickListener(v->showProfile());}
}
